### ISSUE TITLE
Script can't remove content with '&'

### ISSUE THREAD

**Issue by karankashyap** [yuanqing/malarkey#10]
If I insert the content 'Soda & Beers', the script won't be able to remove the content before & and hence 'Soda &' will get appended again and again. Here is an example: 
'Soda & Soda & Soda & Beers'

**Comment by gigaflw** [comment]
I believe this #12 will fix the bug.
It happens because when setting `elem.innerHTML = '&amp'`, a ';' will be automatically appended to  the innerHTML since it is a HTML entity.
Using `elem.textContent` instead will solve this for textContent gets the unencoded text.
