### ISSUE TITLE
Highlight feature

### ISSUE THREAD

**Issue by amit777** [yuanqing/malarkey#7]
Would it be possible to have a highlight-then-delete feature for the word that is typed? Hubspot.com has this. The effect makes it looks like someone is highlighting the word that was typed and then deleting it.

**Comment by yuanqing** [comment]
You can use the [`call`](https://github.com/yuanqing/malarkey#mcallfn) method. The code might look something like:

```js
var m = malarkey(elem, opts);

[ 'foo', 
  'bar', 
  'baz' 
].forEach(function(str) {
  m.type(str)
   .call(function(elem) {
     elem.classList.add('highlighted');
     this();
   })
   .pause()
   .delete()
   .call(function(elem) {
     elem.classList.remove('highlighted');
     this();
   })
   .pause()
});
```

Some simple CSS animations or transitions on the `.highlighted` class should give the desired highlighting effect.
